In [2]:
%%time
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

Wall time: 21.5 s


In [1]:
df = pd.read_csv('student_grades.csv')
df.head()

NameError: name 'pd' is not defined

In [102]:
df.columns

Index(['stud_id', 'course1_marks', 'course2_marks', 'course3_marks',
       'course4_marks', 'good_student'],
      dtype='object')

In [103]:
X = df[['stud_id', 'course1_marks', 'course2_marks', 'course3_marks',
       'course4_marks']].values
X

array([[ 1, 80, 90, 95, 85],
       [ 2, 50, 40, 56, 55],
       [ 3, 43, 58, 33, 49],
       [ 4, 85, 95, 87, 88],
       [ 5, 86, 96, 88, 89],
       [ 6, 87, 80, 90, 68],
       [ 7, 88, 81, 91, 69],
       [ 8, 89, 82, 92, 70],
       [ 9, 90, 83, 93, 71],
       [10, 91, 84, 94, 72],
       [11, 92, 85, 95, 73],
       [12, 93, 86, 96, 74],
       [13, 94, 87, 97, 75],
       [14, 95, 88, 98, 76],
       [15, 96, 89, 99, 77],
       [16, 97, 90, 82, 78],
       [17, 98, 91, 83, 79],
       [18, 99, 92, 81, 80],
       [19, 40, 50, 33, 43],
       [20, 41, 51, 34, 44],
       [21, 42, 52, 35, 45],
       [22, 43, 53, 36, 46],
       [23, 44, 54, 37, 47],
       [24, 45, 55, 38, 48],
       [25, 46, 56, 39, 49],
       [26, 47, 57, 40, 50],
       [27, 48, 58, 41, 51],
       [28, 49, 59, 42, 52],
       [29, 50, 60, 43, 53]], dtype=int64)

In [104]:
Y = df['good_student'].values
Y

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

In [105]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.2,random_state = 4)
print ('Train set:', X_train.shape,  Y_train.shape)
print ('Test set:', X_test.shape,  Y_test.shape)

Train set: (23, 5) (23,)
Test set: (6, 5) (6,)


In [106]:
k = 4
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,Y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=15, p=2,
           weights='uniform')

In [107]:
X_test[0:5]

array([[12, 93, 86, 96, 74],
       [22, 43, 53, 36, 46],
       [28, 49, 59, 42, 52],
       [16, 97, 90, 82, 78],
       [21, 42, 52, 35, 45]], dtype=int64)

In [108]:
yhat = neigh.predict(X_test)
yhat[0:5]

array([1, 0, 0, 1, 0], dtype=int64)